# Generated by Django 4.1.3 on 2022-11-29 22:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=258)),
                ('Type', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField()),
                ('Required_Skills', ckeditor.fields.RichTextField()),
                ('Salary', models.TextField(blank=True)),
                ('Location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobType', models.CharField(blank=True, choices=[('Part-Time', 'Part Time'), ('Full-Time', 'Full Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('National Service', 'National Service')], default='Part-Time', max_length=24)),
                ('Full_Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Brief_introduction_about_yourself', models.TextField()),
                ('Resume', models.FileField(null=True, upload_to='')),
                ('Job_Title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.joblist')),
            ],
        ),
    ]
