# Generated by Django 4.1.3 on 2022-11-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='Job_Title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.joblist'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='Type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
