# Generated by Django 4.1.3 on 2022-11-29 22:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='JobType',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part Time'), ('Full-Time', 'Full Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('National Service', 'National Service')], default='Part-Time', max_length=24),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Job_Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.joblist'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblist',
            name='Type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='Required_Skills',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
