# Generated by Django 4.1.3 on 2022-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_job_title_joblist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='JobType',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part Time'), ('Full-Time', 'Full Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('National Service', 'National Service')], default='Part-Time', max_length=24),
        ),
    ]
