# Generated by Django 4.1.3 on 2022-11-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_jobtype_jobapplication_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='Remarks',
        ),
    ]
