# Generated by Django 4.1.3 on 2022-11-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='Job_Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.joblist'),
        ),
    ]
