# Generated by Django 4.1.3 on 2022-11-24 21:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='Required_Skills',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
