# Generated by Django 4.1.3 on 2022-11-21 18:17

from django.db import migrations, models
import phonenumber_field.modelfields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme', models.CharField(max_length=200)),
                ('University', models.CharField(max_length=300)),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
                ('Role', models.CharField(max_length=250)),
                ('Company', models.CharField(max_length=300)),
                ('Task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Link', models.URLField()),
                ('Link_Name', models.CharField(blank='yes', max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('ScreenShot', sorl.thumbnail.fields.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=130)),
                ('Last_Name', models.CharField(max_length=130)),
                ('Other_Name', models.CharField(blank='yes', max_length=130)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Address', models.CharField(max_length=130)),
                ('Summary', models.TextField()),
                ('Status', models.CharField(blank='yes', max_length=130)),
                ('Profile_Picture', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('Education', models.ManyToManyField(to='personnel.education')),
                ('Experience', models.ManyToManyField(to='personnel.experience')),
                ('Project', models.ManyToManyField(to='personnel.project')),
                ('Skill', models.ManyToManyField(to='personnel.skill')),
            ],
        ),
    ]
