# Generated by Django 4.1.3 on 2022-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='End_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Start_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='End_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Start_Date',
            field=models.DateField(),
        ),
    ]
