# Generated by Django 4.1.3 on 2022-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='End_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Start_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='End_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Start_Date',
            field=models.DateTimeField(),
        ),
    ]
