# Generated by Django 4.1.3 on 2022-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='Gender',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
