# Generated by Django 4.1.3 on 2022-11-23 16:26

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personnel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='Other_Name',
            new_name='Other_Names',
        ),
        migrations.AddField(
            model_name='project',
            name='ScreenShot1',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='ScreenShot2',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='End_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='Start_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='End_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Start_Date',
            field=models.DateField(),
        ),
    ]
