# Generated by Django 4.1.3 on 2022-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_rename_other_name_personnel_other_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='University',
            new_name='Institution',
        ),
        migrations.AddField(
            model_name='project',
            name='Contribution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='End_Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='End_Date',
            field=models.DateField(blank=True),
        ),
    ]
